apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mgmt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shivagande26/argocd-helm-promotion-proj.git'
    targetRevision: HEAD
    path: charts/user-mgmt-service
    helm:
      valueFiles:
        - ../../environments/prod/values-prd.yaml
  destination:
    server: 'https://5922C8F26043BA5BD6F3F07BBF0A13DC.gr7.us-east-1.eks.amazonaws.com:6443'
    namespace: default
  syncPolicy:
    automated: null
