apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mgmt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shivagande26/argocd-helm-promotion-proj.git'
    targetRevision: HEAD
    path: charts/user-mgmt-service
    helm:
      valueFiles:
        - ../../environments/prd/values-prd.yaml
  destination:
    name: uat-test
    namespace: default
  syncPolicy:
    automated: null
