apiVersion: v1
kind: Service
metadata:
  {{- with .Values.userMgmtSvc }}
  name: user-mgmt-svc
  labels:
  {{- include "webapp.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .svcPort }}
      targetPort: {{ .targetPort }}
  selector:
    type: webapp
  {{- end }}